config/routes.rb
Rails.application.routes.draw do
  
  resources :vidros
  
  root 'welcome#index'

end

app/models/door.rb
class Door < ActiveRecord::Base
end

app/models/vidro.rb
class Vidro < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doors_controller.rb
class DoorsController < ApplicationController
  before_action :set_door, only: [:show, :edit, :update, :destroy]

  # GET /doors
  # GET /doors.json
  def index
    @doors = Door.all
  end

  # GET /doors/1
  # GET /doors/1.json
  def show
  end

  # GET /doors/new
  def new
    @door = Door.new
  end

  # GET /doors/1/edit
  def edit
  end

  # POST /doors
  # POST /doors.json
  def create
    @door = Door.new(door_params)

    respond_to do |format|
      if @door.save
        format.html { redirect_to @door, notice: 'Door was successfully created.' }
        format.json { render :show, status: :created, location: @door }
      else
        format.html { render :new }
        format.json { render json: @door.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doors/1
  # PATCH/PUT /doors/1.json
  def update
    respond_to do |format|
      if @door.update(door_params)
        format.html { redirect_to @door, notice: 'Door was successfully updated.' }
        format.json { render :show, status: :ok, location: @door }
      else
        format.html { render :edit }
        format.json { render json: @door.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doors/1
  # DELETE /doors/1.json
  def destroy
    @door.destroy
    respond_to do |format|
      format.html { redirect_to doors_url, notice: 'Door was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_door
      @door = Door.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def door_params
      params.require(:door).permit(:type, :format)
    end
end

app/controllers/vidros_controller.rb
class VidrosController < ApplicationController
    def new
    end
    
    def index
        @vidros = Vidro.all
    end
    
    def show
        @vidro = Vidro.find(params[:id])
    end
    
    def create  
        #render plain: params[:vidros].inspect
        @vidro = Vidro.new(vidro_params)
        
        @vidro.save
        redirect_to vidros_path
    end
    
    private
      def vidro_params
        params.require(:vidro).permit(:title, :text)
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @index = "seja bem vindo!!"
  end
end
#teste

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doors_helper.rb
module DoorsHelper
end

app/helpers/vidros_helper.rb
module VidrosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/doors/_form.html.erb
<%= form_for(@door) do |f| %>
  <% if @door.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@door.errors.count, "error") %> prohibited this door from being saved:</h2>

      <ul>
      <% @door.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :format %><br>
    <%= f.text_field :format %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doors/edit.html.erb
<h1>Editing Door</h1>

<%= render 'form' %>

<%= link_to 'Show', @door %> |
<%= link_to 'Back', doors_path %>

app/views/doors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Doors</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Format</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doors.each do |door| %>
      <tr>
        <td><%= door.type %></td>
        <td><%= door.format %></td>
        <td><%= link_to 'Show', door %></td>
        <td><%= link_to 'Edit', edit_door_path(door) %></td>
        <td><%= link_to 'Destroy', door, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Door', new_door_path %>

app/views/doors/new.html.erb
<h1>New Door</h1>

<%= render 'form' %>

<%= link_to 'Back', doors_path %>

app/views/doors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @door.type %>
</p>

<p>
  <strong>Format:</strong>
  <%= @door.format %>
</p>

<%= link_to 'Edit', edit_door_path(@door) %> |
<%= link_to 'Back', doors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vidros/index.html.erb
<h1>Lista de Vidros</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @vidros.each do |vidro| %>
    <tr>
      <td><%= vidro.title %></td>
      <td><%= vidro.text %></td>
      <td><%= link_to 'Mostrar item', vidro_path(vidro) %></td>
    </tr>
  <% end %>
</table>

app/views/vidros/new.html.erb
<%= form_for :vidro , url: vidros_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
  
<%= link_to "Mostar Vidros", vidros_path %>
<% end %>

app/views/vidros/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @vidro.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @vidro.text %>
</p>

<p><%= link_to 'Voltar', vidros_path %></td></p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p><%= @index %></p>
<%= link_to "Cadastrar Vidros", new_vidro_path %>